name: CI Create Release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
           [tag](https://github.com/release-jf/release-hope/releases/tag/${{ github.ref }})，[CHANGELOG](https://github.com/release-jf/release-hope/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          