name: Main Action

on:
  push:
    branches:
      - "**"
    tags:
      - v**
  pull_request:
    branches:
      - main

jobs:
  build-project:
    name: Build Project
    uses: ./.github/workflows/build-project.yml

  deploy-github-docs:
    name: Deploy GitHub Docs
    # Only triggered on main or work branch
    if: github.ref_name == 'main'
    needs:
      - build-project
    uses: ./.github/workflows/deploy-github-docs.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
  deploy-production:
    name: Deploy Production Docs
    # Only triggered by v2 tag push
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build-project
    uses: ./.github/workflows/release.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      
      