name: Release and Build Docs

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.repository == 'release-jf/release-hope'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:vite-build